services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: LovrDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:123456789@db:3306/LovrDB
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  mysql_data: